In [1]:
import pandas as pd
import numpy as np

In [2]:
carprice = pd.read_excel("carprice.xlsx")
carprice

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [3]:
# First apply pandas get_dummies

In [4]:
dummies = pd.get_dummies(carprice['Car Model'])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [5]:
dummies.drop(['Mercedez Benz C class'],inplace=True,axis='columns')

In [6]:
dummies

Audi A5  BMW X5
0         0       1
1         0       1
2         0       1
3         0       1
4         0       1
5         1       0
6         1       0
7         1       0
8         1       0
9         0       0
10        0       0
11        0       0
12        0       0

In [7]:
# concat both the frames:
merged = pd.concat([carprice,dummies],axis='columns')
merged.head()

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0    BMW X5    69000          18000         6        0       1
1    BMW X5    35000          34000         3        0       1
2    BMW X5    57000          26100         5        0       1
3    BMW X5    22500          40000         2        0       1
4    BMW X5    46000          31500         4        0       1

In [8]:
# drop 1st column
merged = merged.drop(['Car Model'],axis='columns')
merged.head()

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0    69000          18000         6        0       1
1    35000          34000         3        0       1
2    57000          26100         5        0       1
3    22500          40000         2        0       1
4    46000          31500         4        0       1

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lr = LinearRegression()
X = merged.drop(['Sell Price($)'],axis='columns')
y = merged['Sell Price($)']

In [11]:
lr.fit(X,y)

LinearRegression()

In [12]:
lr.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [13]:
# Score of the model
lr.score(X,y)

0.9417050937281083

In [14]:
# last 2 parameters are for Audi & BMW

# price of mercedez 4 year old
lr.predict([[45000,4,0,0]])

array([36991.31721061])

In [15]:
# BMW price - 7 year old & 86000 mileage
lr.predict([[86000,7,0,1]])

array([11080.74313219])

### Lets do the same using One Hot Encoder

In [16]:
df_copy = carprice.copy()
df_copy.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
# First we need to encode the categorical variables to number
le = LabelEncoder()

In [19]:
le.fit_transform(df_copy['Car Model'])

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [20]:
df_copy['Car Model'] = le.fit_transform(df_copy['Car Model'])
df_copy.head(2)

Car Model  Mileage  Sell Price($)  Age(yrs)
0          1    69000          18000         6
1          1    35000          34000         3

In [21]:
# Find X & y

X = df_copy[['Car Model','Mileage','Age(yrs)']].values # using values as we want 2D array
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]], dtype=int64)

In [22]:
y = df_copy['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [23]:
# Now use One Hot Encoder to convert numbers(0-1-2) to binary values {with added 3 columns}, similar to pd.get_dummies.
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')

In [24]:
# this will convert categorical column to binary..  
X = ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [25]:
# dropping the 1st column:
X = X[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [26]:
lr.fit(X,y)

LinearRegression()

In [27]:
# price of mercedez 4 year old
lr.predict([[0,0,45000,4]])

array([34537.77647335])